// Code generated by mockery v2.7.5. DO NOT EDIT.

package mocks

import (
	models "github.com/monitoror/monitoror/models"
	mock "github.com/stretchr/testify/mock"

	params "github.com/monitoror/monitoror/internal/pkg/monitorable/params"
)

// TileEnabler is an autogenerated mock type for the TileEnabler type
type TileEnabler struct {
	mock.Mock
}

// Enable provides a mock function with given fields: variantName, paramsValidator, routePath
func (_m *TileEnabler) Enable(variantName models.VariantName, paramsValidator params.Validator, routePath string) {
	_m.Called(variantName, paramsValidator, routePath)
}
