// Code generated by mockery v1.0.0. DO NOT EDIT.

// If you want to rebuild this file, make mock-monitorable

package mocks

import mock "github.com/stretchr/testify/mock"
import model "github.com/monitoror/monitoror/monitorable/ping/model"

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// CheckPing provides a mock function with given fields: hostname
func (_m *Repository) CheckPing(hostname string) (*model.Ping, error) {
	ret := _m.Called(hostname)

	var r0 *model.Ping
	if rf, ok := ret.Get(0).(func(string) *model.Ping); ok {
		r0 = rf(hostname)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Ping)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(hostname)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
