// Code generated by mockery v1.0.0. DO NOT EDIT.

// If you want to rebuild this file, make mock-monitorable

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import models "github.com/monitoror/monitoror/monitorable/ping/models"

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Ping provides a mock function with given fields: ctx, hostname
func (_m *Repository) Ping(ctx context.Context, hostname string) (*models.Ping, error) {
	ret := _m.Called(ctx, hostname)

	var r0 *models.Ping
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Ping); ok {
		r0 = rf(ctx, hostname)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Ping)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, hostname)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
