// Code generated by mockery v1.0.0. DO NOT EDIT.

// If you want to rebuild this file, make mock-monitorable

package mocks

import mock "github.com/stretchr/testify/mock"
import model "github.com/monitoror/monitoror/monitorable/ping/model"

import tiles "github.com/monitoror/monitoror/models/tiles"

// Usecase is an autogenerated mock type for the Usecase type
type Usecase struct {
	mock.Mock
}

// Ping provides a mock function with given fields: params
func (_m *Usecase) Ping(params *model.PingParams) (*tiles.HealthTile, error) {
	ret := _m.Called(params)

	var r0 *tiles.HealthTile
	if rf, ok := ret.Get(0).(func(*model.PingParams) *tiles.HealthTile); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tiles.HealthTile)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*model.PingParams) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
