// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	net "net"

	mock "github.com/stretchr/testify/mock"
)

// Dialer is an autogenerated mock type for the Dialer type
type Dialer struct {
	mock.Mock
}

// Dial provides a mock function with given fields: network, addr
func (_m *Dialer) Dial(network string, addr string) (net.Conn, error) {
	ret := _m.Called(network, addr)

	var r0 net.Conn
	if rf, ok := ret.Get(0).(func(string, string) net.Conn); ok {
		r0 = rf(network, addr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.Conn)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(network, addr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
