// Code generated by mockery v1.0.0. DO NOT EDIT.

// If you want to rebuild this file, make mock-monitorable

package mocks

import mock "github.com/stretchr/testify/mock"

// FormatedDataProvider is an autogenerated mock type for the FormatedDataProvider type
type FormatedDataProvider struct {
	mock.Mock
}

// GetKey provides a mock function with given fields:
func (_m *FormatedDataProvider) GetKey() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetUnmarshaller provides a mock function with given fields:
func (_m *FormatedDataProvider) GetUnmarshaller() func([]byte, interface{}) error {
	ret := _m.Called()

	var r0 func([]byte, interface{}) error
	if rf, ok := ret.Get(0).(func() func([]byte, interface{}) error); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func([]byte, interface{}) error)
		}
	}

	return r0
}
