// Code generated by mockery v1.0.0. DO NOT EDIT.

// If you want to rebuild this file, make mock-monitorable

package mocks

import mock "github.com/stretchr/testify/mock"

// FormatedDataProvider is an autogenerated mock type for the FormatedDataProvider type
type FormatedDataProvider struct {
	mock.Mock
}

// GetFormat provides a mock function with given fields:
func (_m *FormatedDataProvider) GetFormat() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetKey provides a mock function with given fields:
func (_m *FormatedDataProvider) GetKey() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
