// Code generated by mockery v1.0.0. DO NOT EDIT.

// If you want to rebuild this file, make mock-monitorable

package mocks

import mock "github.com/stretchr/testify/mock"

// StatusCodeRangeProvider is an autogenerated mock type for the StatusCodeRangeProvider type
type StatusCodeRangeProvider struct {
	mock.Mock
}

// GetStatusCodeRange provides a mock function with given fields:
func (_m *StatusCodeRangeProvider) GetStatusCodeRange() (int, int) {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 int
	if rf, ok := ret.Get(1).(func() int); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}
