#!/usr/bin/env bash

# Generate mocks of interfaces find inside all sub-directory of monitorable
for sd in monitorable/*/; do
    rm -rf ${sd}/mocks
    mockery \
      -dir ${sd} \
      -output ${sd}/mocks \
      -all \
      -note "If you want to rebuild this file, make mock-monitorable"
done
