#!/usr/bin/env bash

# Generate mocks of interfaces find inside all sub-directory of monitorable
for dir in monitorable/*/; do
    rm -rf ${dir}/mocks
    mockery \
      -dir ${dir} \
      -output ${dir}/mocks \
      -all \
      -note "If you want to rebuild this file, make mock-monitorable"
done
