// Code generated by mockery v2.7.5. DO NOT EDIT.

package mocks

import (
	build "github.com/jsdidierlaurent/azure-devops-go-api/azuredevops/build"
	mock "github.com/stretchr/testify/mock"

	release "github.com/jsdidierlaurent/azure-devops-go-api/azuredevops/release"
)

// Connection is an autogenerated mock type for the Connection type
type Connection struct {
	mock.Mock
}

// GetBuildConnection provides a mock function with given fields:
func (_m *Connection) GetBuildConnection() (build.Client, error) {
	ret := _m.Called()

	var r0 build.Client
	if rf, ok := ret.Get(0).(func() build.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(build.Client)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetReleaseConnection provides a mock function with given fields:
func (_m *Connection) GetReleaseConnection() (release.Client, error) {
	ret := _m.Called()

	var r0 release.Client
	if rf, ok := ret.Get(0).(func() release.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(release.Client)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
