// Code generated by mockery v1.0.0. DO NOT EDIT.

// If you want to rebuild this file, make mock

package mocks

import (
	models "github.com/monitoror/monitoror/models"
	mock "github.com/stretchr/testify/mock"

	router "github.com/monitoror/monitoror/service/router"
)

// MonitorableRouter is an autogenerated mock type for the MonitorableRouter type
type MonitorableRouter struct {
	mock.Mock
}

// RouterGroup provides a mock function with given fields: path, variant
func (_m *MonitorableRouter) RouterGroup(path string, variant models.VariantName) router.MonitorableRouterGroup {
	ret := _m.Called(path, variant)

	var r0 router.MonitorableRouterGroup
	if rf, ok := ret.Get(0).(func(string, models.VariantName) router.MonitorableRouterGroup); ok {
		r0 = rf(path, variant)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(router.MonitorableRouterGroup)
		}
	}

	return r0
}
