#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail


#######################################################################################
# This script is used by "make version" command for creating new version of monitoror #
#######################################################################################


VERSION_REGEX="^([0-9]*)\\.([0-9]*)\\.([0-9]*)$"
VERSION_FILE=./VERSION

function error {
  echo -e "$1" >&2
  exit 1
}

if [[ -n $(git status -s) ]]; then
  error "You have changed files. Please clean up your git repository"
fi

version=$(cat "$VERSION_FILE" 2>/dev/null)
echo "Current Version: $version"
read -p 'Command (major|minor|patch): ' input

case $input in
  major|minor|patch) command=$input;;
  *) error "Invalid command $input";;
esac

if [[ "$version" =~ $VERSION_REGEX ]]; then
  major=${BASH_REMATCH[1]}
  minor=${BASH_REMATCH[2]}
  patch=${BASH_REMATCH[3]}

  case "$command" in
    major) new="$((major + 1)).0.0";;
    minor) new="${major}.$((minor + 1)).0";;
    patch) new="${major}.${minor}.$((patch + 1))";;
    *) error "Invalid command $command" ;;
  esac
else
  error "Version $version does not match the version scheme 'major.minor.patch'."
fi

# Update VERSION file
echo "New version is $version"
echo $newVersion > "$VERSION_FILE"

# Commit !
git add "$VERSION_FILE"
git commit -m "chore: bump version to $newVersion"





