#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source $DIR/bump-function

#######################################################################################
# This script is used by "make version" command for creating new version of monitoror #
#######################################################################################


VERSION_FILE=./VERSION


if [[ -n $(git status -s) ]]; then
  error "You have changed files. Please clean up your git repository"
fi

version=$(cat "$VERSION_FILE" 2>/dev/null)
echo "Current Version: $version"
read -p 'Command (major|minor|patch): ' input

case $input in
  major|minor|patch) command=$input;;
  *) error "Invalid command $input";;
esac

newVersion=$(bump_version "$version" "$command")

# Update VERSION file
echo "New version is $newVersion"
echo $newVersion > "$VERSION_FILE"

# Commit !
git add "$VERSION_FILE"
git commit -m "chore: bump version to $newVersion"





