#!/usr/bin/env bash

VERSION_REGEX="^([0-9]*)\\.([0-9]*)\\.([0-9]*)$"

function error {
  echo -e "$1" >&2
  exit 1
}

bump_version () {
  if [[ "$1" =~ $VERSION_REGEX ]]; then
    major=${BASH_REMATCH[1]}
    minor=${BASH_REMATCH[2]}
    patch=${BASH_REMATCH[3]}

    case "$2" in
      major) newVersion="$((major + 1)).0.0";;
      minor) newVersion="${major}.$((minor + 1)).0";;
      patch) newVersion="${major}.${minor}.$((patch + 1))";;
      *) error "Invalid command $2" ;;
    esac
  else
    error "Version $1 does not match the version scheme 'major.minor.patch'."
  fi

  echo "$newVersion"
}






