#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail


########################################################################################
# This script is used by "make release" command for releasing new version of monitoror #
########################################################################################


VERSION_FILE=./VERSION

function error {
  echo -e "$1" >&2
  exit 1
}

# Check if repository is dirty
if [[ -n $(git status -s) ]]; then
  error "You have changed files. Please clean up your git directory."
fi

git checkout master

# Check if master is sync with origin master
if [[ $(git rev-parse origin/master) != $(git rev-parse HEAD) ]]; then
  error "Local is not sync with origin remote, please sync before release"
fi

git pull --rebase origin master

version=$(cat "$VERSION_FILE" 2>/dev/null)
git tag "$version"
