#!/usr/bin/env bash

set -eu -o pipefail

source ./scripts/.variables
export LDFLAGS="\
    -w \
    -X \"github.com/monitoror/monitoror/cli/version.GitCommit=${GITCOMMIT}\" \
    -X \"github.com/monitoror/monitoror/cli/version.BuildTime=2017-01-09 22:45:00+00:00\" \
    -X \"github.com/monitoror/monitoror/cli/version.Version=faker\" \
    ${LDFLAGS:-} \
"

MO_ENV=${MO_ENV:-"development"} go run --ldflags "${LDFLAGS}" -tags faker "${SOURCE}"
