// Code generated by mockery v1.0.0. DO NOT EDIT.

// If you want to rebuild this file, make mock-pkg

package mocks

import builder "github.com/monitoror/monitoror/pkg/monitoror/builder"
import mock "github.com/stretchr/testify/mock"

// DynamicTileBuilder is an autogenerated mock type for the DynamicTileBuilder type
type DynamicTileBuilder struct {
	mock.Mock
}

// ListDynamicTile provides a mock function with given fields: params
func (_m *DynamicTileBuilder) ListDynamicTile(params interface{}) ([]builder.Result, error) {
	ret := _m.Called(params)

	var r0 []builder.Result
	if rf, ok := ret.Get(0).(func(interface{}) []builder.Result); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]builder.Result)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
