// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import model "github.com/monitoror/monitoror/monitorable/travisci/model"

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Build provides a mock function with given fields: ctx, group, repository, branch
func (_m *Repository) Build(ctx context.Context, group string, repository string, branch string) (*model.Build, error) {
	ret := _m.Called(ctx, group, repository, branch)

	var r0 *model.Build
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *model.Build); ok {
		r0 = rf(ctx, group, repository, branch)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Build)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, group, repository, branch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
