// Code generated by mockery v1.0.0. DO NOT EDIT.

// If you want to rebuild this file, make mock-monitorable

package mocks

import builder "github.com/monitoror/monitoror/pkg/monitoror/builder"
import mock "github.com/stretchr/testify/mock"
import models "github.com/monitoror/monitoror/monitorable/pingdom/models"

import tiles "github.com/monitoror/monitoror/models/tiles"

// Usecase is an autogenerated mock type for the Usecase type
type Usecase struct {
	mock.Mock
}

// Check provides a mock function with given fields: params
func (_m *Usecase) Check(params *models.CheckParams) (*tiles.HealthTile, error) {
	ret := _m.Called(params)

	var r0 *tiles.HealthTile
	if rf, ok := ret.Get(0).(func(*models.CheckParams) *tiles.HealthTile); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tiles.HealthTile)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*models.CheckParams) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListDynamicTile provides a mock function with given fields: params
func (_m *Usecase) ListDynamicTile(params interface{}) ([]builder.Result, error) {
	ret := _m.Called(params)

	var r0 []builder.Result
	if rf, ok := ret.Get(0).(func(interface{}) []builder.Result); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]builder.Result)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
