// Code generated by mockery v1.0.0. DO NOT EDIT.

// If you want to rebuild this file, make mock

package mocks

import (
	context "context"

	github "github.com/google/go-github/github"

	mock "github.com/stretchr/testify/mock"
)

// ChecksService is an autogenerated mock type for the ChecksService type
type ChecksService struct {
	mock.Mock
}

// ListCheckRunsForRef provides a mock function with given fields: ctx, owner, repo, ref, opt
func (_m *ChecksService) ListCheckRunsForRef(ctx context.Context, owner string, repo string, ref string, opt *github.ListCheckRunsOptions) (*github.ListCheckRunsResults, *github.Response, error) {
	ret := _m.Called(ctx, owner, repo, ref, opt)

	var r0 *github.ListCheckRunsResults
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, *github.ListCheckRunsOptions) *github.ListCheckRunsResults); ok {
		r0 = rf(ctx, owner, repo, ref, opt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.ListCheckRunsResults)
		}
	}

	var r1 *github.Response
	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, *github.ListCheckRunsOptions) *github.Response); ok {
		r1 = rf(ctx, owner, repo, ref, opt)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*github.Response)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, string, string, string, *github.ListCheckRunsOptions) error); ok {
		r2 = rf(ctx, owner, repo, ref, opt)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
