// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	github "github.com/google/go-github/github"

	mock "github.com/stretchr/testify/mock"
)

// PullRequestService is an autogenerated mock type for the PullRequestService type
type PullRequestService struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx, owner, repo, number
func (_m *PullRequestService) Get(ctx context.Context, owner string, repo string, number int) (*github.PullRequest, *github.Response, error) {
	ret := _m.Called(ctx, owner, repo, number)

	var r0 *github.PullRequest
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) *github.PullRequest); ok {
		r0 = rf(ctx, owner, repo, number)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.PullRequest)
		}
	}

	var r1 *github.Response
	if rf, ok := ret.Get(1).(func(context.Context, string, string, int) *github.Response); ok {
		r1 = rf(ctx, owner, repo, number)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*github.Response)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, string, string, int) error); ok {
		r2 = rf(ctx, owner, repo, number)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// List provides a mock function with given fields: ctx, owner, repo, opt
func (_m *PullRequestService) List(ctx context.Context, owner string, repo string, opt *github.PullRequestListOptions) ([]*github.PullRequest, *github.Response, error) {
	ret := _m.Called(ctx, owner, repo, opt)

	var r0 []*github.PullRequest
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *github.PullRequestListOptions) []*github.PullRequest); ok {
		r0 = rf(ctx, owner, repo, opt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*github.PullRequest)
		}
	}

	var r1 *github.Response
	if rf, ok := ret.Get(1).(func(context.Context, string, string, *github.PullRequestListOptions) *github.Response); ok {
		r1 = rf(ctx, owner, repo, opt)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*github.Response)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, string, string, *github.PullRequestListOptions) error); ok {
		r2 = rf(ctx, owner, repo, opt)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
