// Code generated by mockery v1.0.0. DO NOT EDIT.

// If you want to rebuild this file, make mock-monitorable

package mocks

import (
	builder "github.com/monitoror/monitoror/pkg/monitoror/builder"

	mock "github.com/stretchr/testify/mock"

	models "github.com/monitoror/monitoror/models"

	utils "github.com/monitoror/monitoror/pkg/monitoror/utils"
)

// Manager is an autogenerated mock type for the Manager type
type Manager struct {
	mock.Mock
}

// EnableDynamicTile provides a mock function with given fields: tileType, variant, Validator, _a3
func (_m *Manager) EnableDynamicTile(tileType models.TileType, variant string, Validator utils.Validator, _a3 builder.DynamicTileBuilder) {
	_m.Called(tileType, variant, Validator, _a3)
}

// EnableTile provides a mock function with given fields: tileType, variant, validator, path, initialMaxDelay
func (_m *Manager) EnableTile(tileType models.TileType, variant string, validator utils.Validator, path string, initialMaxDelay int) {
	_m.Called(tileType, variant, validator, path, initialMaxDelay)
}

// RegisterTile provides a mock function with given fields: tileType, variant, version
func (_m *Manager) RegisterTile(tileType models.TileType, variant []string, version string) {
	_m.Called(tileType, variant, version)
}
