// Code generated by mockery v1.0.0. DO NOT EDIT.

// If you want to rebuild this file, make mock-monitorable

package mocks

import (
	config "github.com/monitoror/monitoror/api/config"
	mock "github.com/stretchr/testify/mock"

	models "github.com/monitoror/monitoror/models"

	validator "github.com/monitoror/monitoror/pkg/validator"
)

// Manager is an autogenerated mock type for the Manager type
type Manager struct {
	mock.Mock
}

// EnableDynamicTile provides a mock function with given fields: tileType, variant, Validator, builder
func (_m *Manager) EnableDynamicTile(tileType models.TileType, variant models.Variant, Validator validator.SimpleValidator, builder config.DynamicTileBuilder) {
	_m.Called(tileType, variant, Validator, builder)
}

// EnableTile provides a mock function with given fields: tileType, variant, _a2, path, initialMaxDelay
func (_m *Manager) EnableTile(tileType models.TileType, variant models.Variant, _a2 validator.SimpleValidator, path string, initialMaxDelay int) {
	_m.Called(tileType, variant, _a2, path, initialMaxDelay)
}

// RegisterTile provides a mock function with given fields: tileType, variants, version
func (_m *Manager) RegisterTile(tileType models.TileType, variants []models.Variant, version string) {
	_m.Called(tileType, variants, version)
}
