// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	models "github.com/monitoror/monitoror/api/config/models"
	mock "github.com/stretchr/testify/mock"
)

// ParamsValidator is an autogenerated mock type for the ParamsValidator type
type ParamsValidator struct {
	mock.Mock
}

// Validate provides a mock function with given fields: currentVersion
func (_m *ParamsValidator) Validate(currentVersion *models.ConfigVersion) *models.ConfigError {
	ret := _m.Called(currentVersion)

	var r0 *models.ConfigError
	if rf, ok := ret.Get(0).(func(*models.ConfigVersion) *models.ConfigError); ok {
		r0 = rf(currentVersion)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ConfigError)
		}
	}

	return r0
}
