// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	configmodels "github.com/monitoror/monitoror/api/config/models"
	mock "github.com/stretchr/testify/mock"

	models "github.com/monitoror/monitoror/models"
)

// TileGeneratorEnabler is an autogenerated mock type for the TileGeneratorEnabler type
type TileGeneratorEnabler struct {
	mock.Mock
}

// Enable provides a mock function with given fields: variant, generatorParamsValidator, tileGeneratorFunction
func (_m *TileGeneratorEnabler) Enable(variant models.VariantName, generatorParamsValidator configmodels.ParamsValidator, tileGeneratorFunction configmodels.TileGeneratorFunction) {
	_m.Called(variant, generatorParamsValidator, tileGeneratorFunction)
}
