// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	pingdom "github.com/jsdidierlaurent/go-pingdom/pingdom"
	mock "github.com/stretchr/testify/mock"
)

// PingdomTransactionCheckAPI is an autogenerated mock type for the PingdomTransactionCheckAPI type
type PingdomTransactionCheckAPI struct {
	mock.Mock
}

// List provides a mock function with given fields: params
func (_m *PingdomTransactionCheckAPI) List(params ...map[string]string) ([]pingdom.TransactionCheckResponse, error) {
	_va := make([]interface{}, len(params))
	for _i := range params {
		_va[_i] = params[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 []pingdom.TransactionCheckResponse
	if rf, ok := ret.Get(0).(func(...map[string]string) []pingdom.TransactionCheckResponse); ok {
		r0 = rf(params...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]pingdom.TransactionCheckResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(...map[string]string) error); ok {
		r1 = rf(params...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Read provides a mock function with given fields: id
func (_m *PingdomTransactionCheckAPI) Read(id int) (*pingdom.TransactionCheckResponse, error) {
	ret := _m.Called(id)

	var r0 *pingdom.TransactionCheckResponse
	if rf, ok := ret.Get(0).(func(int) *pingdom.TransactionCheckResponse); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pingdom.TransactionCheckResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
