// Code generated by mockery v1.0.0. DO NOT EDIT.

// If you want to rebuild this file, make mock-monitorable

package mocks

import mock "github.com/stretchr/testify/mock"

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// CheckPort provides a mock function with given fields: hostname, _a1
func (_m *Repository) CheckPort(hostname string, _a1 int) error {
	ret := _m.Called(hostname, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int) error); ok {
		r0 = rf(hostname, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
