// Code generated by mockery v1.0.0. DO NOT EDIT.

// If you want to rebuild this file, make mock-monitorable

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// OpenSocket provides a mock function with given fields: ctx, hostname, _a2
func (_m *Repository) OpenSocket(ctx context.Context, hostname string, _a2 int) error {
	ret := _m.Called(ctx, hostname, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) error); ok {
		r0 = rf(ctx, hostname, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
