// Code generated by mockery v1.0.0. DO NOT EDIT.

// If you want to rebuild this file, make mock-pkg

package mocks

import gitlab "github.com/xanzy/go-gitlab"

import mock "github.com/stretchr/testify/mock"

// CommitsService is an autogenerated mock type for the CommitsService type
type CommitsService struct {
	mock.Mock
}

// GetCommit provides a mock function with given fields: pid, sha, options
func (_m *CommitsService) GetCommit(pid interface{}, sha string, options ...gitlab.OptionFunc) (*gitlab.Commit, *gitlab.Response, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, pid, sha)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *gitlab.Commit
	if rf, ok := ret.Get(0).(func(interface{}, string, ...gitlab.OptionFunc) *gitlab.Commit); ok {
		r0 = rf(pid, sha, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gitlab.Commit)
		}
	}

	var r1 *gitlab.Response
	if rf, ok := ret.Get(1).(func(interface{}, string, ...gitlab.OptionFunc) *gitlab.Response); ok {
		r1 = rf(pid, sha, options...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*gitlab.Response)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(interface{}, string, ...gitlab.OptionFunc) error); ok {
		r2 = rf(pid, sha, options...)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
