// Code generated by mockery v1.0.0. DO NOT EDIT.

// If you want to rebuild this file, make mock-pkg

package mocks

import gitlab "github.com/xanzy/go-gitlab"

import mock "github.com/stretchr/testify/mock"

// SearchService is an autogenerated mock type for the SearchService type
type SearchService struct {
	mock.Mock
}

// Issues provides a mock function with given fields: query, opt, options
func (_m *SearchService) Issues(query string, opt *gitlab.SearchOptions, options ...gitlab.OptionFunc) ([]*gitlab.Issue, *gitlab.Response, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, query, opt)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 []*gitlab.Issue
	if rf, ok := ret.Get(0).(func(string, *gitlab.SearchOptions, ...gitlab.OptionFunc) []*gitlab.Issue); ok {
		r0 = rf(query, opt, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*gitlab.Issue)
		}
	}

	var r1 *gitlab.Response
	if rf, ok := ret.Get(1).(func(string, *gitlab.SearchOptions, ...gitlab.OptionFunc) *gitlab.Response); ok {
		r1 = rf(query, opt, options...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*gitlab.Response)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(string, *gitlab.SearchOptions, ...gitlab.OptionFunc) error); ok {
		r2 = rf(query, opt, options...)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
