// Code generated by mockery v1.0.0. DO NOT EDIT.

// If you want to rebuild this file, make mock-monitorable

package mocks

import mock "github.com/stretchr/testify/mock"
import tiles "github.com/monitoror/monitoror/models/tiles"
import utils "github.com/monitoror/monitoror/pkg/monitoror/utils"

// Helper is an autogenerated mock type for the Helper type
type Helper struct {
	mock.Mock
}

// RegisterTile provides a mock function with given fields: tileType, path, validator
func (_m *Helper) RegisterTile(tileType tiles.TileType, path string, validator utils.Validator) {
	_m.Called(tileType, path, validator)
}
