// Code generated by mockery v1.0.0. DO NOT EDIT.

// If you want to rebuild this file, make mock-monitorable

package mocks

import mock "github.com/stretchr/testify/mock"
import tiles "github.com/monitoror/monitoror/models/tiles"
import validator "github.com/monitoror/monitoror/pkg/monitoror/validator"

// Helper is an autogenerated mock type for the Helper type
type Helper struct {
	mock.Mock
}

// RegisterTile provides a mock function with given fields: tileType, path, _a2
func (_m *Helper) RegisterTile(tileType tiles.TileType, path string, _a2 validator.Validator) {
	_m.Called(tileType, path, _a2)
}

// RegisterTileWithConfigVariant provides a mock function with given fields: tileType, configVariant, path, _a3
func (_m *Helper) RegisterTileWithConfigVariant(tileType tiles.TileType, configVariant string, path string, _a3 validator.Validator) {
	_m.Called(tileType, configVariant, path, _a3)
}
