// Code generated by mockery v1.0.0. DO NOT EDIT.

// If you want to rebuild this file, make mock-monitorable

package mocks

import builder "github.com/monitoror/monitoror/pkg/monitoror/builder"

import mock "github.com/stretchr/testify/mock"
import models "github.com/monitoror/monitoror/models"
import utils "github.com/monitoror/monitoror/pkg/monitoror/utils"

// Helper is an autogenerated mock type for the Helper type
type Helper struct {
	mock.Mock
}

// RegisterDynamicTile provides a mock function with given fields: tileType, validator, _a2
func (_m *Helper) RegisterDynamicTile(tileType models.TileType, validator utils.Validator, _a2 builder.DynamicTileBuilder) {
	_m.Called(tileType, validator, _a2)
}

// RegisterDynamicTileWithConfigVariant provides a mock function with given fields: tileType, configVariant, validator, _a3
func (_m *Helper) RegisterDynamicTileWithConfigVariant(tileType models.TileType, configVariant string, validator utils.Validator, _a3 builder.DynamicTileBuilder) {
	_m.Called(tileType, configVariant, validator, _a3)
}

// RegisterTile provides a mock function with given fields: tileType, validator, path
func (_m *Helper) RegisterTile(tileType models.TileType, validator utils.Validator, path string) {
	_m.Called(tileType, validator, path)
}

// RegisterTileWithConfigVariant provides a mock function with given fields: tileType, variant, validator, path
func (_m *Helper) RegisterTileWithConfigVariant(tileType models.TileType, variant string, validator utils.Validator, path string) {
	_m.Called(tileType, variant, validator, path)
}
