// Code generated by mockery v1.0.0. DO NOT EDIT.

// If you want to rebuild this file, make mock-monitorable

package mocks

import mock "github.com/stretchr/testify/mock"
import tiles "github.com/monitoror/monitoror/models/tiles"
import utils "github.com/monitoror/monitoror/pkg/monitoror/utils"

// Regiterer is an autogenerated mock type for the Regiterer type
type Regiterer struct {
	mock.Mock
}

// Register provides a mock function with given fields: tileType, path, configValidator
func (_m *Regiterer) Register(tileType tiles.TileType, path string, configValidator utils.Validator) {
	_m.Called(tileType, path, configValidator)
}
