// Code generated by mockery v1.0.0. DO NOT EDIT.

// If you want to rebuild this file, make mock-monitorable

package mocks

import mock "github.com/stretchr/testify/mock"
import models "github.com/monitoror/monitoror/monitorable/config/models"

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// GetConfigFromPath provides a mock function with given fields: _a0
func (_m *Repository) GetConfigFromPath(_a0 string) (*models.Config, error) {
	ret := _m.Called(_a0)

	var r0 *models.Config
	if rf, ok := ret.Get(0).(func(string) *models.Config); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Config)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetConfigFromUrl provides a mock function with given fields: _a0
func (_m *Repository) GetConfigFromUrl(_a0 string) (*models.Config, error) {
	ret := _m.Called(_a0)

	var r0 *models.Config
	if rf, ok := ret.Get(0).(func(string) *models.Config); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Config)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
