// Code generated by mockery v1.0.0. DO NOT EDIT.

// If you want to rebuild this file, make mock-monitorable

package mocks

import (
	builder "github.com/monitoror/monitoror/pkg/monitoror/builder"

	mock "github.com/stretchr/testify/mock"

	models "github.com/monitoror/monitoror/monitorable/config/models"

	monitorormodels "github.com/monitoror/monitoror/models"

	utils "github.com/monitoror/monitoror/pkg/monitoror/utils"
)

// Usecase is an autogenerated mock type for the Usecase type
type Usecase struct {
	mock.Mock
}

// GetConfig provides a mock function with given fields: params
func (_m *Usecase) GetConfig(params *models.ConfigParams) (*models.Config, error) {
	ret := _m.Called(params)

	var r0 *models.Config
	if rf, ok := ret.Get(0).(func(*models.ConfigParams) *models.Config); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Config)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*models.ConfigParams) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Hydrate provides a mock function with given fields: _a0
func (_m *Usecase) Hydrate(_a0 *models.Config) {
	_m.Called(_a0)
}

// RegisterDynamicTile provides a mock function with given fields: tileType, validator, _a2
func (_m *Usecase) RegisterDynamicTile(tileType monitorormodels.TileType, validator utils.Validator, _a2 builder.DynamicTileBuilder) {
	_m.Called(tileType, validator, _a2)
}

// RegisterDynamicTileWithConfigVariant provides a mock function with given fields: tileType, configVariant, validator, _a3
func (_m *Usecase) RegisterDynamicTileWithConfigVariant(tileType monitorormodels.TileType, configVariant string, validator utils.Validator, _a3 builder.DynamicTileBuilder) {
	_m.Called(tileType, configVariant, validator, _a3)
}

// RegisterTile provides a mock function with given fields: tileType, validator, path
func (_m *Usecase) RegisterTile(tileType monitorormodels.TileType, validator utils.Validator, path string) {
	_m.Called(tileType, validator, path)
}

// RegisterTileWithConfigVariant provides a mock function with given fields: tileType, variant, validator, path
func (_m *Usecase) RegisterTileWithConfigVariant(tileType monitorormodels.TileType, variant string, validator utils.Validator, path string) {
	_m.Called(tileType, variant, validator, path)
}

// Verify provides a mock function with given fields: _a0
func (_m *Usecase) Verify(_a0 *models.Config) {
	_m.Called(_a0)
}
