#!/usr/bin/env bash

set -e

# Executing test coverage and print it
go clean testdata ./...
rm -f coverage.txt coverage.html
gotestsum -- -coverprofile=coverage.txt -covermode=atomic `go list ./... | grep -v mocks`
go tool cover -html=coverage.txt -o coverage.html
