#!/usr/bin/env bash

# Executing test coverage and print it
go clean testdata ./...
gotestsum -- -coverprofile=cover.out `go list ./... | grep -v mocks`
go tool cover -html=cover.out -o cover.html
rm cover.out
