#!/usr/bin/env bash

# Executing test coverage and print it
go clean testdata ./...
rm -f coverage.txt coverage.html
gotestsum -- -coverprofile=coverage.txt `go list ./... | grep -v mocks`
go tool cover -html=coverage.txt -o coverage.html
