#!/usr/bin/env bash

# Executing test coverage and print it
go clean testdata ./...
rm -f cover.out
gotestsum -- -cover -coverprofile=coverage.txt -covermode=atomic `go list ./... | grep -v mocks`
go tool cover -func coverage.txt
