// Code generated by mockery v1.0.0. DO NOT EDIT.

// If you want to rebuild this file, make mock-monitorable

package mocks

import mock "github.com/stretchr/testify/mock"
import models "github.com/monitoror/monitoror/monitorable/jenkins/models"

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// GetLastBuildStatus provides a mock function with given fields: jobId
func (_m *Repository) GetLastBuildStatus(jobId string) (*models.Build, error) {
	ret := _m.Called(jobId)

	var r0 *models.Build
	if rf, ok := ret.Get(0).(func(string) *models.Build); ok {
		r0 = rf(jobId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Build)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(jobId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
