---
name: lint

on:
  pull_request:

jobs:
  core-lint:
    name: Core / Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - uses: reviewdog/action-golangci-lint@v1
        with:
          github_token: ${{ secrets.github_token }}
          golangci_lint_flags: "--config=.golangci.yml"
          tool_name: Core / Lint report

  ui-lint:
    name: UI / Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: install
        working-directory: ui
        run: yarn install

      - name: lint
        working-directory: ui
        run: yarn lint

  chmod:
    name: Check chmods
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: check
        run: |
          # All files, except scripts, should not be executable (644)
          wrongChmodFiles="$(find . -type f -not -path '*/\.git/*' -not -path './scripts/*' -not -perm 0644)"

          # All scripts should be executable (755)
          wrongChmodScripts="$(find ./scripts -type f -not -path '*/\.git/*' -not -perm 0755)"

          # Print file with wrong chmod
          echo "" # Blank line
          [[ -n "$wrongChmodFiles" ]] && (echo "Chmod should be 644 on those files:" && echo "$wrongChmodFiles" && echo "")
          [[ -n "$wrongChmodScripts" ]] && (echo "Chmod should be 755 on those files:" && echo "$wrongChmodScripts" && echo "")

          [[ -z "$wrongChmodFiles$wrongChmodScripts" ]]
