// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PingModel is an autogenerated mock type for the PingModel type
type PingModel struct {
	mock.Mock
}

// Ping provides a mock function with given fields: host
func (_m *PingModel) Ping(host string) (string, error) {
	ret := _m.Called(host)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(host)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(host)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
